const { Case, Hearing } = require('../models');
const { nextCin } = require('../services/counterService');
const { hearingsForCase } = require('../services/hearingService');
const { serializeCase, serializeHearing } = require('../services/serializers');
const { badRequest, notFound, conflict } = require('../utils/errors');
const { requireStrings, requireDates } = require('../utils/validate');

const TEXT_FIELDS = [
  'defendantName',
  'defendantAddress',
  'crimeType',
  'committedLocation',
  'arrestingOfficer',
  'judgeName',
  'publicProsecutor',
  'lawyerName',
];
const DATE_FIELDS = ['committedDate', 'arrestDate', 'startDate', 'expectedCompletionDate'];

async function findCaseOr404(cin) {
  const c = await Case.findOne({ cin });
  if (!c) throw notFound('CASE_NOT_FOUND', `No case with CIN "${cin}".`);
  return c;
}

async function registerCase(req, res) {
  const body = req.body || {};
  // The CIN is always generated by the server; a client-supplied one is rejected.
  if (body.cin !== undefined) {
    throw badRequest('CIN_NOT_ALLOWED', 'The CIN is generated by the system and must not be supplied.');
  }
  const text = requireStrings(body, TEXT_FIELDS);
  const dates = requireDates(body, DATE_FIELDS);

  if (dates.arrestDate < dates.committedDate) {
    throw badRequest('INVALID_DATE_ORDER', 'Arrest date cannot be before the date the crime was committed.');
  }
  if (dates.expectedCompletionDate < dates.startDate) {
    throw badRequest('INVALID_DATE_ORDER', 'Expected completion date cannot be before the case starting date.');
  }

  const created = await Case.create({
    ...text,
    ...dates,
    cin: await nextCin(),
    status: 'REGISTERED', // status is decided by the server only
    judgmentDate: null,
    judgmentSummary: null,
  });
  res.status(201).json(serializeCase(created));
}

async function getCase(req, res) {
  const c = await findCaseOr404(req.params.cin);
  const hearings = await hearingsForCase(c.cin);
  res.json({ ...serializeCase(c), hearings: hearings.map(serializeHearing) });
}

async function closeCase(req, res) {
  const c = await findCaseOr404(req.params.cin);
  const { judgmentSummary } = requireStrings(req.body, ['judgmentSummary']);
  const { judgmentDate } = requireDates(req.body, ['judgmentDate']);

  if (c.status === 'CLOSED') throw conflict('CASE_ALREADY_CLOSED', 'This case is already closed.');
  if (await Hearing.exists({ cin: c.cin, status: 'SCHEDULED' })) {
    throw conflict(
      'HEARING_OUTSTANDING',
      'The case has a scheduled hearing. Record its proceedings (or adjourn it) before closing.'
    );
  }
  if (c.status !== 'PENDING') {
    throw conflict('INVALID_CASE_STATE', 'Proceedings must be recorded for at least one hearing before judgment.');
  }
  if (judgmentDate < c.startDate) {
    throw badRequest('INVALID_DATE_ORDER', 'Judgment date cannot be before the case starting date.');
  }

  // Conditional update guards against two registrars closing the same case at once.
  const updated = await Case.findOneAndUpdate(
    { cin: c.cin, status: 'PENDING' },
    { $set: { status: 'CLOSED', judgmentDate, judgmentSummary } },
    { new: true }
  );
  if (!updated) throw conflict('CASE_ALREADY_CLOSED', 'This case is already closed.');
  res.json(serializeCase(updated));
}

async function updateCase(req, res) {
  const c = await findCaseOr404(req.params.cin);
  const text = requireStrings(req.body, TEXT_FIELDS);
  const dates = requireDates(req.body, DATE_FIELDS);

  if (dates.arrestDate < dates.committedDate) {
    throw badRequest('INVALID_DATE_ORDER', 'Arrest date cannot be before the date the crime was committed.');
  }
  if (dates.expectedCompletionDate < dates.startDate) {
    throw badRequest('INVALID_DATE_ORDER', 'Expected completion date cannot be before the case starting date.');
  }

  Object.assign(c, text, dates);
  await c.save();
  res.json(serializeCase(c));
}

module.exports = { registerCase, getCase, updateCase, closeCase, findCaseOr404 };
