import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../services/api.js';
import { ErrorMessage, Field, PageHeader } from '../../components/common.jsx';

const FIELDS = [
  { name: 'defendantName', label: 'Defendant name' },
  { name: 'defendantAddress', label: 'Defendant address' },
  { name: 'crimeType', label: 'Crime type' },
  { name: 'committedDate', label: 'Date crime was committed', type: 'date' },
  { name: 'committedLocation', label: 'Location crime was committed' },
  { name: 'arrestingOfficer', label: 'Arresting officer' },
  { name: 'arrestDate', label: 'Arrest date', type: 'date' },
  { name: 'judgeName', label: 'Presiding judge' },
  { name: 'publicProsecutor', label: 'Public prosecutor' },
  { name: 'lawyerName', label: 'Lawyer' },
  { name: 'startDate', label: 'Case starting date', type: 'date' },
  { name: 'expectedCompletionDate', label: 'Expected completion date', type: 'date' },
];

const EMPTY = Object.fromEntries(FIELDS.map((f) => [f.name, '']));

export function validateCase(form) {
  const errs = {};
  for (const f of FIELDS) if (!String(form[f.name] || '').trim()) errs[f.name] = 'Required';
  if (form.committedDate && form.arrestDate && form.arrestDate < form.committedDate) {
    errs.arrestDate = 'Cannot be before the crime date';
  }
  if (form.startDate && form.expectedCompletionDate && form.expectedCompletionDate < form.startDate) {
    errs.expectedCompletionDate = 'Cannot be before the start date';
  }
  return errs;
}

export default function NewCasePage() {
  const [form, setForm] = useState(EMPTY);
  const [errors, setErrors] = useState({});
  const [error, setError] = useState(null);
  const [created, setCreated] = useState(null);
  const [busy, setBusy] = useState(false);

  async function handleSubmit(e) {
    e.preventDefault();
    const errs = validateCase(form);
    setErrors(errs);
    if (Object.keys(errs).length) return;
    setBusy(true);
    setError(null);
    try {
      const body = Object.fromEntries(Object.entries(form).map(([k, v]) => [k, v.trim()]));
      setCreated(await api.registerCase(body));
    } catch (err) {
      setError(err);
    } finally {
      setBusy(false);
    }
  }

  if (created) {
    return (
      <>
        <PageHeader title="Case registered" />
        <section className="card narrow">
          <p>The system generated the following Case Identification Number:</p>
          <Field label="CIN">
            <input className="cin-display" value={created.cin} readOnly aria-readonly="true" data-testid="generated-cin" />
          </Field>
          <div className="actions">
            <Link className="btn btn-primary" to={`/registrar/cases/${encodeURIComponent(created.cin)}`}>
              Schedule first hearing
            </Link>
            <button
              type="button"
              className="btn"
              onClick={() => {
                setCreated(null);
                setForm(EMPTY);
              }}
            >
              Register another case
            </button>
          </div>
        </section>
      </>
    );
  }

  return (
    <>
      <PageHeader title="Register a case" subtitle="The CIN is generated by the system after submission." />
      <ErrorMessage error={error} />
      <form className="card" onSubmit={handleSubmit} noValidate>
        <div className="form-grid">
          {FIELDS.map((f) => (
            <Field key={f.name} label={f.label} error={errors[f.name]}>
              <input
                type={f.type || 'text'}
                name={f.name}
                value={form[f.name]}
                onChange={(e) => setForm({ ...form, [f.name]: e.target.value })}
              />
            </Field>
          ))}
        </div>
        <div className="actions">
          <button className="btn btn-primary" disabled={busy}>
            {busy ? 'Registering…' : 'Register case'}
          </button>
        </div>
      </form>
    </>
  );
}
